version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: myPostgresDb
    restart: always
    ports:
      - '5433:5432'
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=admin"
    volumes:
      - ./scriptMatches.sql:/docker-entrypoint-initdb.d/scriptMatches.sql
  app:
    build: .
    command: npm start
    ports: 
      - '8087:8087'
    volumes:
      - .:/app
    depends_on:
      - db
