
version: '3.7'
services:
  db-jogos:
    image: postgres:latest
    container_name: myPostgresDb
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./scriptMatches.sql:/docker-entrypoint-initdb.d/scriptMatches.sql
  api:
    image: matgoulart1996/trab2_tp6-api:latest
    container_name: api-node
    ports:
      - '8087:8087'
    working_dir: /app
    volumes:
      - .:/app
    command: npm start