name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out de repo
        uses: actions/checkout@v3
      
      - name: Publish to Docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: matgoulart1996/trab2_tp6-api
          tags: latest, ${{ github.run_number }}
